# Generated by Django 5.2.3 on 2025-09-20 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energymonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='hora',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='consumo_energia',
            field=models.FloatField(default=0.0),
        ),
    ]
