# Generated by Django 5.2.3 on 2025-10-07 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energymonitor', '0002_remove_sensordata_fecha_remove_sensordata_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='consumo_energia',
            new_name='corriente',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='energia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='factor_potencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='frecuencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='potencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='voltaje',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humedad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperatura',
            field=models.FloatField(default=0.0),
        ),
    ]
