# Generated by Django 5.2.3 on 2025-10-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energymonitor', '0003_rename_consumo_energia_sensordata_corriente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='corriente',
            new_name='consumo_energia',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='energia',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='factor_potencia',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='voltaje',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humedad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperatura',
            field=models.FloatField(),
        ),
    ]
